export const titles: string[] = [
  "Ambassador",
  "Administrator",
  "Bureaucrat",
  "Chairperson",
  "Chief Officer",
  "Commissioner",
  "Comptroller",
  "Coordinator",
  "Czar",
  "Deputy Director",
  "Director",
  "Executive",
  "Foreman",
  "Guardian",
  "Head",
  "Inspector",
  "Judge",
  "King",
  "Leader",
  "Liason",
  "Manager",
  "Minister",
  "Navigator",
  "Ombudsman",
  "Overseer",
  "President",
  "Queen",
  "Representative",
  "Scapegoat",
  "Secretary",
  "Selectman",
  "Supervisor",
  "Treasurer",
  "Usurper",
  "Victor",
  "Wrangler",
  "Yardmaster",
];

export const orgs: string[] = [
  "Alliance",
  "Assembly",
  "Band",
  "Board",
  "Breakfast Club",
  "Circle",
  "Club",
  "Colony",
  "Committee",
  "Congregation",
  "Consortium",
  "Council",
  "Crew",
  "Delegation",
  "Department",
  "Faction",
  "Federation",
  "Foundation",
  "Gang",
  "Gathering",
  "Group",
  "Guild",
  "Hangout",
  "Institute",
  "Jury",
  "League",
  "Meeting",
  "Network",
  "Operation",
  "Pact",
  "Panel",
  "Partnership",
  "Posse",
  "Quest",
  "Realm",
  "Squad",
  "Task Force",
  "Team",
  "Tribe",
  "Union",
  "World",
];

export const orgJoiners: string[] = ["against", "for", "of"];

export const responsibilities: string[] = [
  "Agriculture",
  "Alchemy",
  "Alien Communication",
  "Art and Culture",
  "Artificial Inaptitude",
  "Artificial Intelligence",
  "Basketweaving",
  "Chocolate Distribution",
  "Climate Control",
  "Coffee Supply",
  "Community Engagement",
  "Crosswalk Safety",
  "Cultural Affairs",
  "Cybersecurity",
  "Diplomatic Incidents",
  "Disaster Response",
  "Dogwalking",
  "Education",
  "EinsteIn-Rosen bridges",
  "Entertainment",
  "Environmental Conservation",
  "Event Planning",
  "Finance",
  "Food Services",
  "Happiness",
  "Healthcare",
  "Historical Preservation",
  "Human Resources",
  "Innovation",
  "Intelligence",
  "Intergalactic Affairs",
  "Legal Affairs",
  "Marine Biology",
  "Marketing",
  "Paranormal Activity",
  "Public Relations",
  "Public Safety",
  "Quantum Displacement",
  "Reality TV",
  "Renewable Energy",
  "Research and Development",
  "Reticulating Splines",
  "Social Media",
  "Space Exploration",
  "Sports",
  "Technology",
  "Teleportation",
  "Time Travel",
  "Tourism",
  "Transportation",
  "Urban Development",
  "Virtual Reality",
  "Wellness",
];
