import React from "react";
import {
  Box,
  Typography,
  List,
  ListItem,
  ListItemText,
  Paper,
} from "@mui/material";

const PartySetupOverview: React.FC = () => {
  return (
    <Box sx={{ textAlign: "left", p: 2 }}>
      <Typography variant="h5" gutterBottom>
        Overview of Political Party Creation
      </Typography>
      <Typography variant="body1" paragraph>
        Welcome to the Political Party Creation section of our ranked choice
        voting simulator. Here, you can configure the political landscape for
        your simulation, defining the parties, their relationships, and how they
        interact during elections. We offer two modes to suit different levels
        of customization: Simple and Advanced.
      </Typography>

      <Typography variant="h5" gutterBottom>
        Understanding Coalitions and Relationships
      </Typography>
      <Typography variant="body1" paragraph>
        In ranked choice voting (RCV), voters rank candidates in order of
        preference. Since RCV requires multiple choices, party coalitions and
        relationships play a critical role in guiding how a voter might make
        their choices. These relationships help simulate realistic voting
        behavior by influencing the order in which voters rank candidates,
        especially in scenarios where their preferred candidate is eliminated.
      </Typography>
      <Typography variant="body1" paragraph>
        <strong>Coalitions</strong>: Represent alliances where parties support
        each other, influencing voters to rank candidates from allied parties
        higher.
      </Typography>
      <Typography variant="body1" paragraph>
        <strong>Oppositions</strong>: Represent adversarial relationships where
        parties oppose each other, leading voters to rank candidates from
        opposing parties lower or not at all.
      </Typography>

      <Typography variant="h5" gutterBottom>
        Simple Mode
      </Typography>
      <Typography variant="body1" paragraph>
        In Simple Mode, you can quickly set up the political environment by
        specifying the number of parties. The relationships between the parties
        are autogenerated based on predefined rules and heuristics. This mode is
        ideal for users who want to get started quickly without delving into the
        complexities of political dynamics.
      </Typography>
      <Typography variant="h6" gutterBottom>
        Steps to Use Simple Mode
      </Typography>
      <List>
        <ListItem>
          <ListItemText
            primary="Set the Number of Parties"
            secondary="Use the slider to choose the desired number of political parties for your simulation."
          />
        </ListItem>
        <ListItem>
          <ListItemText
            primary="Autogenerate Relationships"
            secondary="Our system will automatically generate relationships between the parties based on typical political alignments and opposition logic."
          />
        </ListItem>
      </List>
      <Typography variant="h6" gutterBottom>
        Example
      </Typography>
      <Typography variant="body1" paragraph>
        If you set the number of parties to 5, the system might generate a setup
        with 3 major parties and 2 minor parties, with predefined relationships
        such as coalitions and oppositions.
      </Typography>

      <Typography variant="h5" gutterBottom>
        Advanced Mode
      </Typography>
      <Typography variant="body1" paragraph>
        In Advanced Mode, you have full control over the political landscape.
        You can create a custom graph of political parties, defining all the
        relationships and interactions. This mode is perfect for users who want
        to simulate specific political scenarios or experiment with different
        political structures.
      </Typography>
      <Typography variant="h6" gutterBottom>
        Steps to Use Advanced Mode
      </Typography>
      <List>
        <ListItem>
          <ListItemText
            primary="Create Parties"
            secondary="Manually add parties to the simulation, assigning them colors and categories (major, minor, fringe)."
          />
        </ListItem>
        <ListItem>
          <ListItemText
            primary="Define Relationships"
            secondary="Draw connections between parties to define coalitions and oppositions. Specify the strength of these relationships using weights."
          />
        </ListItem>
      </List>
      <Typography variant="h6" gutterBottom>
        Coalition Potential
      </Typography>
      <Typography variant="body1" paragraph>
        Coalition potential refers to the likelihood or ability of different
        political parties to form alliances or coalitions. In multi-party
        systems, where no single party has an outright majority, parties often
        need to collaborate to form a stable government. Coalition potential is
        influenced by ideological proximity, strategic interests, and historical
        relationships.
      </Typography>
      <Typography variant="h6" gutterBottom>
        Example
      </Typography>
      <Typography variant="body1" paragraph>
        In the United States, the Green Party and the Democratic Party might
        form a coalition on environmental issues, despite having differences in
        other areas. This coalition potential is higher because both parties
        prioritize environmental policies.
      </Typography>
      <Typography variant="h6" gutterBottom>
        Defining Relationships
      </Typography>
      <Typography variant="body1" paragraph>
        <strong>Coalitions</strong>: Represent alliances where parties support
        each other. For example, a coalition between the Green Party and the
        Democratic Party might have a high coalition potential due to shared
        values on environmental policies.
      </Typography>
      <Typography variant="body1" paragraph>
        <strong>Oppositions</strong>: Represent adversarial relationships where
        parties oppose each other. For instance, the Republican Party and the
        Democratic Party in the U.S. are often in opposition on many policy
        issues.
      </Typography>
      <Typography variant="h6" gutterBottom>
        Example of a Custom Graph
      </Typography>
      <Typography variant="body1" paragraph>
        Create a graph with major parties (Red, Blue, Yellow), minor parties
        (Green, Orange, Purple), and fringe parties (Teal, Pink, Gold). Define
        that Red and Blue are in opposition. Set Green and Yellow to have a
        coalition potential with a weight indicating the strength of their
        alliance. Define random but weighted relationships for fringe parties to
        major and minor parties.
      </Typography>

      <Typography variant="body1" paragraph>
        By using Simple Mode, you can quickly set up your simulation and start
        exploring ranked choice voting dynamics. For a more tailored experience,
        Advanced Mode allows you to dive deep into political relationships and
        test various scenarios. Enjoy experimenting with the political
        landscapes and observing how different configurations impact election
        outcomes!
      </Typography>
    </Box>
  );
};

export default PartySetupOverview;
